// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: engine.proto

package enginepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request-level failure taxonomy. These are errors the engine raises while serving a single
// request (not startup/load failures, which abort the process before any RPC). The message field
// carries human-readable detail (counts, limits) that the Go layer surfaces verbatim to the client.
type ErrorCode int32

const (
	ErrorCode_ERROR_CODE_UNSPECIFIED   ErrorCode = 0
	ErrorCode_ERROR_CODE_OVER_CAPACITY ErrorCode = 1 // KV pool / request queue is full — retryable (maps to HTTP 503)
	ErrorCode_ERROR_CODE_INTERNAL      ErrorCode = 2 // unexpected engine failure (maps to HTTP 502)
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0: "ERROR_CODE_UNSPECIFIED",
		1: "ERROR_CODE_OVER_CAPACITY",
		2: "ERROR_CODE_INTERNAL",
	}
	ErrorCode_value = map[string]int32{
		"ERROR_CODE_UNSPECIFIED":   0,
		"ERROR_CODE_OVER_CAPACITY": 1,
		"ERROR_CODE_INTERNAL":      2,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_engine_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_engine_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{0}
}

type GenerateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InputIds      []int32                `protobuf:"varint,1,rep,packed,name=input_ids,json=inputIds,proto3" json:"input_ids,omitempty"`               // prompt token ids
	MaxTokens     int32                  `protobuf:"varint,2,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`                   // cap on generated tokens
	Temperature   float32                `protobuf:"fixed32,3,opt,name=temperature,proto3" json:"temperature,omitempty"`                               // <=0 => greedy
	TopP          float32                `protobuf:"fixed32,4,opt,name=top_p,json=topP,proto3" json:"top_p,omitempty"`                                 // nucleus cutoff (1.0 => off)
	StopTokenIds  []int32                `protobuf:"varint,5,rep,packed,name=stop_token_ids,json=stopTokenIds,proto3" json:"stop_token_ids,omitempty"` // stop as soon as one of these is sampled
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateRequest) Reset() {
	*x = GenerateRequest{}
	mi := &file_engine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateRequest) ProtoMessage() {}

func (x *GenerateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateRequest.ProtoReflect.Descriptor instead.
func (*GenerateRequest) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateRequest) GetInputIds() []int32 {
	if x != nil {
		return x.InputIds
	}
	return nil
}

func (x *GenerateRequest) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *GenerateRequest) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *GenerateRequest) GetTopP() float32 {
	if x != nil {
		return x.TopP
	}
	return 0
}

func (x *GenerateRequest) GetStopTokenIds() []int32 {
	if x != nil {
		return x.StopTokenIds
	}
	return nil
}

type Done struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	FinishReason     string                 `protobuf:"bytes,1,opt,name=finish_reason,json=finishReason,proto3" json:"finish_reason,omitempty"` // "stop" (hit a stop id) | "length" (max_tokens / context full)
	PromptTokens     int32                  `protobuf:"varint,2,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	CompletionTokens int32                  `protobuf:"varint,3,opt,name=completion_tokens,json=completionTokens,proto3" json:"completion_tokens,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Done) Reset() {
	*x = Done{}
	mi := &file_engine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Done) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Done) ProtoMessage() {}

func (x *Done) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Done.ProtoReflect.Descriptor instead.
func (*Done) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{1}
}

func (x *Done) GetFinishReason() string {
	if x != nil {
		return x.FinishReason
	}
	return ""
}

func (x *Done) GetPromptTokens() int32 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *Done) GetCompletionTokens() int32 {
	if x != nil {
		return x.CompletionTokens
	}
	return 0
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=flashqwen.ErrorCode" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // detailed, human-readable; surfaced to the client as-is
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_engine_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{2}
}

func (x *Error) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_ERROR_CODE_UNSPECIFIED
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GenerateEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*GenerateEvent_TokenId
	//	*GenerateEvent_Done
	//	*GenerateEvent_Error
	Event         isGenerateEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateEvent) Reset() {
	*x = GenerateEvent{}
	mi := &file_engine_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateEvent) ProtoMessage() {}

func (x *GenerateEvent) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateEvent.ProtoReflect.Descriptor instead.
func (*GenerateEvent) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{3}
}

func (x *GenerateEvent) GetEvent() isGenerateEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *GenerateEvent) GetTokenId() int32 {
	if x != nil {
		if x, ok := x.Event.(*GenerateEvent_TokenId); ok {
			return x.TokenId
		}
	}
	return 0
}

func (x *GenerateEvent) GetDone() *Done {
	if x != nil {
		if x, ok := x.Event.(*GenerateEvent_Done); ok {
			return x.Done
		}
	}
	return nil
}

func (x *GenerateEvent) GetError() *Error {
	if x != nil {
		if x, ok := x.Event.(*GenerateEvent_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isGenerateEvent_Event interface {
	isGenerateEvent_Event()
}

type GenerateEvent_TokenId struct {
	TokenId int32 `protobuf:"varint,1,opt,name=token_id,json=tokenId,proto3,oneof"` // one generated token id
}

type GenerateEvent_Done struct {
	Done *Done `protobuf:"bytes,2,opt,name=done,proto3,oneof"` // terminal event on success (always last)
}

type GenerateEvent_Error struct {
	Error *Error `protobuf:"bytes,3,opt,name=error,proto3,oneof"` // terminal event on failure (mutually exclusive with done)
}

func (*GenerateEvent_TokenId) isGenerateEvent_Event() {}

func (*GenerateEvent_Done) isGenerateEvent_Event() {}

func (*GenerateEvent_Error) isGenerateEvent_Event() {}

type ModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelRequest) Reset() {
	*x = ModelRequest{}
	mi := &file_engine_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelRequest) ProtoMessage() {}

func (x *ModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelRequest.ProtoReflect.Descriptor instead.
func (*ModelRequest) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{4}
}

type ModelInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MaxCtx        int32                  `protobuf:"varint,2,opt,name=max_ctx,json=maxCtx,proto3" json:"max_ctx,omitempty"`
	VocabSize     int32                  `protobuf:"varint,3,opt,name=vocab_size,json=vocabSize,proto3" json:"vocab_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelInfo) Reset() {
	*x = ModelInfo{}
	mi := &file_engine_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelInfo) ProtoMessage() {}

func (x *ModelInfo) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelInfo.ProtoReflect.Descriptor instead.
func (*ModelInfo) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{5}
}

func (x *ModelInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ModelInfo) GetMaxCtx() int32 {
	if x != nil {
		return x.MaxCtx
	}
	return 0
}

func (x *ModelInfo) GetVocabSize() int32 {
	if x != nil {
		return x.VocabSize
	}
	return 0
}

var File_engine_proto protoreflect.FileDescriptor

const file_engine_proto_rawDesc = "" +
	"\n" +
	"\fengine.proto\x12\tflashqwen\"\xaa\x01\n" +
	"\x0fGenerateRequest\x12\x1b\n" +
	"\tinput_ids\x18\x01 \x03(\x05R\binputIds\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x02 \x01(\x05R\tmaxTokens\x12 \n" +
	"\vtemperature\x18\x03 \x01(\x02R\vtemperature\x12\x13\n" +
	"\x05top_p\x18\x04 \x01(\x02R\x04topP\x12$\n" +
	"\x0estop_token_ids\x18\x05 \x03(\x05R\fstopTokenIds\"}\n" +
	"\x04Done\x12#\n" +
	"\rfinish_reason\x18\x01 \x01(\tR\ffinishReason\x12#\n" +
	"\rprompt_tokens\x18\x02 \x01(\x05R\fpromptTokens\x12+\n" +
	"\x11completion_tokens\x18\x03 \x01(\x05R\x10completionTokens\"K\n" +
	"\x05Error\x12(\n" +
	"\x04code\x18\x01 \x01(\x0e2\x14.flashqwen.ErrorCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x86\x01\n" +
	"\rGenerateEvent\x12\x1b\n" +
	"\btoken_id\x18\x01 \x01(\x05H\x00R\atokenId\x12%\n" +
	"\x04done\x18\x02 \x01(\v2\x0f.flashqwen.DoneH\x00R\x04done\x12(\n" +
	"\x05error\x18\x03 \x01(\v2\x10.flashqwen.ErrorH\x00R\x05errorB\a\n" +
	"\x05event\"\x0e\n" +
	"\fModelRequest\"S\n" +
	"\tModelInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\amax_ctx\x18\x02 \x01(\x05R\x06maxCtx\x12\x1d\n" +
	"\n" +
	"vocab_size\x18\x03 \x01(\x05R\tvocabSize*^\n" +
	"\tErrorCode\x12\x1a\n" +
	"\x16ERROR_CODE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18ERROR_CODE_OVER_CAPACITY\x10\x01\x12\x17\n" +
	"\x13ERROR_CODE_INTERNAL\x10\x022\x87\x01\n" +
	"\x06Engine\x12B\n" +
	"\bGenerate\x12\x1a.flashqwen.GenerateRequest\x1a\x18.flashqwen.GenerateEvent0\x01\x129\n" +
	"\bGetModel\x12\x17.flashqwen.ModelRequest\x1a\x14.flashqwen.ModelInfoB\x1dZ\x1bflashqwen/internal/enginepbb\x06proto3"

var (
	file_engine_proto_rawDescOnce sync.Once
	file_engine_proto_rawDescData []byte
)

func file_engine_proto_rawDescGZIP() []byte {
	file_engine_proto_rawDescOnce.Do(func() {
		file_engine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_engine_proto_rawDesc), len(file_engine_proto_rawDesc)))
	})
	return file_engine_proto_rawDescData
}

var file_engine_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_engine_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_engine_proto_goTypes = []any{
	(ErrorCode)(0),          // 0: flashqwen.ErrorCode
	(*GenerateRequest)(nil), // 1: flashqwen.GenerateRequest
	(*Done)(nil),            // 2: flashqwen.Done
	(*Error)(nil),           // 3: flashqwen.Error
	(*GenerateEvent)(nil),   // 4: flashqwen.GenerateEvent
	(*ModelRequest)(nil),    // 5: flashqwen.ModelRequest
	(*ModelInfo)(nil),       // 6: flashqwen.ModelInfo
}
var file_engine_proto_depIdxs = []int32{
	0, // 0: flashqwen.Error.code:type_name -> flashqwen.ErrorCode
	2, // 1: flashqwen.GenerateEvent.done:type_name -> flashqwen.Done
	3, // 2: flashqwen.GenerateEvent.error:type_name -> flashqwen.Error
	1, // 3: flashqwen.Engine.Generate:input_type -> flashqwen.GenerateRequest
	5, // 4: flashqwen.Engine.GetModel:input_type -> flashqwen.ModelRequest
	4, // 5: flashqwen.Engine.Generate:output_type -> flashqwen.GenerateEvent
	6, // 6: flashqwen.Engine.GetModel:output_type -> flashqwen.ModelInfo
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_engine_proto_init() }
func file_engine_proto_init() {
	if File_engine_proto != nil {
		return
	}
	file_engine_proto_msgTypes[3].OneofWrappers = []any{
		(*GenerateEvent_TokenId)(nil),
		(*GenerateEvent_Done)(nil),
		(*GenerateEvent_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_engine_proto_rawDesc), len(file_engine_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_engine_proto_goTypes,
		DependencyIndexes: file_engine_proto_depIdxs,
		EnumInfos:         file_engine_proto_enumTypes,
		MessageInfos:      file_engine_proto_msgTypes,
	}.Build()
	File_engine_proto = out.File
	file_engine_proto_goTypes = nil
	file_engine_proto_depIdxs = nil
}
