// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.12.4
// source: engine.proto

package enginepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Engine_Generate_FullMethodName = "/flashqwen.Engine/Generate"
	Engine_GetModel_FullMethodName = "/flashqwen.Engine/GetModel"
)

// EngineClient is the client API for Engine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The token-level inference engine. The Go app owns all model-text concerns (chat template,
// tokenisation, special tokens, tool-call detection); the C++ engine is a pure executor —
// token ids in, sampled token ids out. It stops when it samples one of stop_token_ids or hits
// max_tokens, and is otherwise unaware of token semantics.
type EngineClient interface {
	// One prompt (token ids) -> a stream of generated token ids, then a final Done.
	Generate(ctx context.Context, in *GenerateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GenerateEvent], error)
	// Engine metadata (authoritative max_ctx after rounding/KV limits, vocab) for clamping + /v1/models.
	// The engine loads the model before binding its port, so a successful GetModel also signals
	// readiness; the client polls it until it answers. Load progress goes to the engine's stderr.
	GetModel(ctx context.Context, in *ModelRequest, opts ...grpc.CallOption) (*ModelInfo, error)
}

type engineClient struct {
	cc grpc.ClientConnInterface
}

func NewEngineClient(cc grpc.ClientConnInterface) EngineClient {
	return &engineClient{cc}
}

func (c *engineClient) Generate(ctx context.Context, in *GenerateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GenerateEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Engine_ServiceDesc.Streams[0], Engine_Generate_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GenerateRequest, GenerateEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Engine_GenerateClient = grpc.ServerStreamingClient[GenerateEvent]

func (c *engineClient) GetModel(ctx context.Context, in *ModelRequest, opts ...grpc.CallOption) (*ModelInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModelInfo)
	err := c.cc.Invoke(ctx, Engine_GetModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EngineServer is the server API for Engine service.
// All implementations must embed UnimplementedEngineServer
// for forward compatibility.
//
// The token-level inference engine. The Go app owns all model-text concerns (chat template,
// tokenisation, special tokens, tool-call detection); the C++ engine is a pure executor —
// token ids in, sampled token ids out. It stops when it samples one of stop_token_ids or hits
// max_tokens, and is otherwise unaware of token semantics.
type EngineServer interface {
	// One prompt (token ids) -> a stream of generated token ids, then a final Done.
	Generate(*GenerateRequest, grpc.ServerStreamingServer[GenerateEvent]) error
	// Engine metadata (authoritative max_ctx after rounding/KV limits, vocab) for clamping + /v1/models.
	// The engine loads the model before binding its port, so a successful GetModel also signals
	// readiness; the client polls it until it answers. Load progress goes to the engine's stderr.
	GetModel(context.Context, *ModelRequest) (*ModelInfo, error)
	mustEmbedUnimplementedEngineServer()
}

// UnimplementedEngineServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEngineServer struct{}

func (UnimplementedEngineServer) Generate(*GenerateRequest, grpc.ServerStreamingServer[GenerateEvent]) error {
	return status.Error(codes.Unimplemented, "method Generate not implemented")
}
func (UnimplementedEngineServer) GetModel(context.Context, *ModelRequest) (*ModelInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetModel not implemented")
}
func (UnimplementedEngineServer) mustEmbedUnimplementedEngineServer() {}
func (UnimplementedEngineServer) testEmbeddedByValue()                {}

// UnsafeEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EngineServer will
// result in compilation errors.
type UnsafeEngineServer interface {
	mustEmbedUnimplementedEngineServer()
}

func RegisterEngineServer(s grpc.ServiceRegistrar, srv EngineServer) {
	// If the following call panics, it indicates UnimplementedEngineServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Engine_ServiceDesc, srv)
}

func _Engine_Generate_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GenerateRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EngineServer).Generate(m, &grpc.GenericServerStream[GenerateRequest, GenerateEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Engine_GenerateServer = grpc.ServerStreamingServer[GenerateEvent]

func _Engine_GetModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServer).GetModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Engine_GetModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServer).GetModel(ctx, req.(*ModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Engine_ServiceDesc is the grpc.ServiceDesc for Engine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Engine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "flashqwen.Engine",
	HandlerType: (*EngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetModel",
			Handler:    _Engine_GetModel_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Generate",
			Handler:       _Engine_Generate_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "engine.proto",
}
