// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.12.4
// source: inference.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Inference_Generate_FullMethodName = "/flashqwen.Inference/Generate"
	Inference_GetModel_FullMethodName = "/flashqwen.Inference/GetModel"
)

// InferenceClient is the client API for Inference service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The model-side inference service. The Go gateway sends structured chat requests; the C++ engine
// owns everything model-specific (Qwen3 chat template, tokenisation, generation, and tool-call
// detection) and streams back typed events. The gateway has zero model knowledge.
type InferenceClient interface {
	// One chat request -> a stream of events (text deltas, completed tool calls, then a final Done).
	Generate(ctx context.Context, in *GenerateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GenerateEvent], error)
	// Model metadata for /v1/models.
	GetModel(ctx context.Context, in *ModelRequest, opts ...grpc.CallOption) (*ModelInfo, error)
}

type inferenceClient struct {
	cc grpc.ClientConnInterface
}

func NewInferenceClient(cc grpc.ClientConnInterface) InferenceClient {
	return &inferenceClient{cc}
}

func (c *inferenceClient) Generate(ctx context.Context, in *GenerateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GenerateEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Inference_ServiceDesc.Streams[0], Inference_Generate_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GenerateRequest, GenerateEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Inference_GenerateClient = grpc.ServerStreamingClient[GenerateEvent]

func (c *inferenceClient) GetModel(ctx context.Context, in *ModelRequest, opts ...grpc.CallOption) (*ModelInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModelInfo)
	err := c.cc.Invoke(ctx, Inference_GetModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InferenceServer is the server API for Inference service.
// All implementations must embed UnimplementedInferenceServer
// for forward compatibility.
//
// The model-side inference service. The Go gateway sends structured chat requests; the C++ engine
// owns everything model-specific (Qwen3 chat template, tokenisation, generation, and tool-call
// detection) and streams back typed events. The gateway has zero model knowledge.
type InferenceServer interface {
	// One chat request -> a stream of events (text deltas, completed tool calls, then a final Done).
	Generate(*GenerateRequest, grpc.ServerStreamingServer[GenerateEvent]) error
	// Model metadata for /v1/models.
	GetModel(context.Context, *ModelRequest) (*ModelInfo, error)
	mustEmbedUnimplementedInferenceServer()
}

// UnimplementedInferenceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInferenceServer struct{}

func (UnimplementedInferenceServer) Generate(*GenerateRequest, grpc.ServerStreamingServer[GenerateEvent]) error {
	return status.Error(codes.Unimplemented, "method Generate not implemented")
}
func (UnimplementedInferenceServer) GetModel(context.Context, *ModelRequest) (*ModelInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetModel not implemented")
}
func (UnimplementedInferenceServer) mustEmbedUnimplementedInferenceServer() {}
func (UnimplementedInferenceServer) testEmbeddedByValue()                   {}

// UnsafeInferenceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InferenceServer will
// result in compilation errors.
type UnsafeInferenceServer interface {
	mustEmbedUnimplementedInferenceServer()
}

func RegisterInferenceServer(s grpc.ServiceRegistrar, srv InferenceServer) {
	// If the following call panics, it indicates UnimplementedInferenceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Inference_ServiceDesc, srv)
}

func _Inference_Generate_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GenerateRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(InferenceServer).Generate(m, &grpc.GenericServerStream[GenerateRequest, GenerateEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Inference_GenerateServer = grpc.ServerStreamingServer[GenerateEvent]

func _Inference_GetModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferenceServer).GetModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Inference_GetModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InferenceServer).GetModel(ctx, req.(*ModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Inference_ServiceDesc is the grpc.ServiceDesc for Inference service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Inference_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "flashqwen.Inference",
	HandlerType: (*InferenceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetModel",
			Handler:    _Inference_GetModel_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Generate",
			Handler:       _Inference_Generate_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "inference.proto",
}
